### ISSUE TITLE
Autocompletion with TAB

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-cli#108]
I would propose to support standard autocompletion pattern with tab.

For example:
* complete "snet co" after pressing tab to "snet contract"
* complete "snet contract M" after pressing tab to "snet contract MultiPartyEscrow"
* etc...

It should be a way to do it very easily since we are using standard argparse library. However I coudn't find a fast way to do it....

**Comment by arturgontijo** [comment]
I'd like to suggest `argcomplete` as we are using `argparse`.
The implementation is simple as:
```
import sys
import argcomplete

from snet_cli import arguments
from snet_cli.config import conf

__version__ = "0.1.6"


def main():
    argv = sys.argv[1:]
    parser = arguments.get_root_parser(conf)
    argcomplete.autocomplete(parser)
    try:
        args = parser.parse_args(argv)
...
```
The downside is that user must enable the global completion by:
`register-python-argcomplete snet >> ~/.bashrc`
or
`echo 'eval "$(register-python-argcomplete snet)"' >> ~/.bashrc`

And then:
`source ~/.bashrc`

IMO put this at README will be better than inside `snet` code.

**Comment by Dinesh2521** [comment]
As @arturgontijo mentioned, argcomplete should be  fine for implementing auto completion. It will help with commands/sub commands auto completion.

There are 2 types of auto completion, which we may require in our CLI
i. Commands/Sub commands - comes by default with argcomplete package. 
ii. Choices/Options we can pass as arguments (Few things comes by default, but we may need to write **custom completers for our CLI specific choices/options**.)

Here is the package for more details
https://pypi.org/project/argcomplete/

**good**
- works well with Linux. Yet to validate on MacOS(Mostly it may work on MacOS as well)
- commands auto complete can be enabled easily 
- it can be used for main commands and sub commands as well
- we can do both arguments and option completers
- it will give us options to write custom completers, so that we can pull choices list from the services, local files, or any other sources 


**bad**
- will not work with Windows OS. Need to modify the the source to enable support for windows
- doesn't offer all parameters auto complete, but we can extend it by using custom completers
- will not offer recommended options or suggestions like AWSCli or few other CLI programs. it does very basic.

**Comment by raamb** [comment]
PR #222 provides this functionality now
