### ISSUE TITLE
Add an option to set a price and add endpoints to the init_metadata command

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-cli#152]
It was suggested to have additional options in `metadata_init` commands to set price or list of endpoints in one command instead of using many commands. Such interface seems more logical for people. This is to discuss such option.

**Comment by astroseger** [comment]
I've added it in #148.
There are two additional options in ```snet service metadata init```  ```--endpoints``` and ```--fixed-price```, both of them are optional.
- --fixed-price is optional because in the future we will have several possible pricing models. 
- --endpoints could be made obligatory, but for now they are optional.

if you have single payment group you can create your metadata in one shot:
```
snet service metadata_init <proto_dir> <service_display_name> <payment_address> --fixed_price <fixed_price> --endpoints <your endpoints>
```

**Comment by astroseger** [comment]
was close in #148
