### ISSUE TITLE
snet-cli cannot use opened channel after service metadata update

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-cli#164]
Not sure it is reproducible on latest version but reproducible on latest release 0.1.9

Steps to reproduce:
- publish 'proto+grpc' service using 'json' encoding in metadata
- open payment channel
- call service, deserialization error is returned as expected
- update service metadata using correct encoding 'proto'
- call service
expected: service returns answer
actual: service answers with deserialization error

Reason: snet-cli cache contains metadata copy which has old 'proto' encoding
If cache is cleaned up then attempt to call service leads to "channel is not initialized" error.

**Comment by astroseger** [comment]
There is a questions how to better deal with it. The general solution is to remove old "channel" directory and initialize channel again (download service metadata and protobuf model). However we cannot check the service metadata from registry at each call because it would be very slow. 

The simple solution is to add ```--force``` flag to ```snet channel init```. So the user will have possibility to manually reinitialize the channel  (but how he would know that he should do it?).

**Comment by vsbogd** [comment]
How do you detect that "channel is not initialized"? What information about channel is kept in cache?

**Comment by astroseger** [comment]
"channel is not initialized" then directory which correspond to this channel doesn't exists.  But it is not a problem. Problem is how to detect that proto files have changed in ipfs. 

Chain of events is following:

1. Client has initialized channel and work with server.
2. Server change proto file in Registry.
3. In this situation the client should reinitialize the channel (get new metatada and get new protofiles). 
now he can do it like this:
     - Remove channel directory (which is bad because user don't know which directory to remove)
     - intilize channel again using ```snet channel init```
If we implement ```--force``` user will be able to simply call ```snet channel init --force``` (in this case he don't need to know which directory to remove)

But ```--force``` doesn't solve the main problem --- how to detect that proto file has changed? We cannot check Registry at each call because it is too slow. We cannot rely on error, because call can actually work with old proto file... So.... I don't know... I don't want to check registry at each call because it will slow down  everything, but it seems it is the only one solution.... Damn it!

**Comment by astroseger** [comment]
I can actually check Registry at each time then call fail (for any reason) and update metadata and protofile if needed, but it will not solve problem entirely.

**Comment by vsbogd** [comment]
Possible solution is introducing API version between client and service. For instance introduce new metadata field to represent API version. It can reflect compatibility, for instance major version means incompatible change when client update is required, and minor version mean that update is not required if client uses old functionality. This version can be kept in metadata and server will read and check it with sent by client one.

**Comment by vsbogd** [comment]
Actually both, updated description above

**Comment by astroseger** [comment]
After discussion with @ferrouswheel and Ramon on slack the proposed solution is following:
- Save service metadataURI
- In ```snet client call``` at each call check that metadataURI hasn't been changed. If so reinitialize service
- Have special flag ```-no-registry-check``` to skip this check
