### ISSUE TITLE
Make `snet service init` use float argument for AGI price

### ISSUE THREAD

**Issue by erickearns** [singnet/snet-cli#27]
Prompt currently claims it expects the price in AGI, but it appears to actually be in `10 ** -8` AGI.

**Comment by ferrouswheel** [comment]
Exact prompt is `Choose a price in AGI to call your service: (default: 0)`.

Agree that this is confusing and needs to either auto-convert to the AGI minimum unit, or be clear it's in units of `10^-8`.

Should also have a sensible default instead of 0. I think 1 AGI should be the default i.e. `1x10^8` of the minimum divisible unit.

**Comment by astroseger** [comment]
We have the term for 10^-8 AGI : 'cogs'  (see AGI token contract). So I propose to replace 
```bash
Choose a price in AGI to call your service: (default: 0)
```
with
```bash
Choose a price in cogs (cogs = 10^-8 AGI) to call your service: (default: 0)
```
I'm writing the code for publishing the service in MPE payment system. And I was going to use the term cogs.
